FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# Sample API

>**IMPORTANT:**  Because the Kensium Payments API uses its [own unique API keys for request authentication](#apikey) and provides its own [Test and Production accounts](#goinglive), you should never click the **SIGN UP** or **LOGIN** buttons at the top right of the Developer Center navigation, as these are used strictly for the other APIs on the Developer Center. Please contact your business relationship manager or reach out to <integrations@kensium.com> for API keys and Test/Production accounts.

Polls is a simple API allowing consumers to view polls and vote in them. Polls is a simple API allowing consumers to view polls and vote in them. Polls is a simple API allowing consumers to view polls and vote in them. Polls is a simple API allowing consumers to view polls and vote in them.

* Polls is a simple API allowing consumers to view polls and vote in them.
* Polls is a simple API allowing consumers to view polls and vote in them.
* Polls is a simple API allowing consumers to view polls and vote in them.

## Sample Attributes

| Element            | Type   |Required| Description                                                                                         |
|--------------------|--------|---------|-----------------------------------------------------------------------------------------------------|
| id                 | string |Read Only| This is the response id returned by the processor                                                     |
| responseId         | string |Read Only| This is the response ID assigned by Credorax.                                                       |
| requestId          | string |Read Only| This is the request ID assigned by Kensium.                                                         |
| description        | string |Read Only| This is a description of the response.                                                              |
| authCode           | string |Read Only| This is the authorization code.                                                                     |
| txnDateTime        | string |Read Only| This is the transaction date and time.                                                              |
| referenceNbr       | string |Read Only| This is the Bank net transaction ID/Merch Tran Ref                                                  |
| responseReasonCode | string |Read Only| This is the raw response reason code returned by Credorax.                                          |
| cvvVerification    | enum   |Read Only| This is the response to the cvv submitted with the transaction request. Possible values are:<ul><li>MATCH</li><li>NO_MATCH</li><li>NO_MATCH</li><li>NOT_PROCESSED</li><li>UNKNOWN</li></ul> |
| cvv2Result         | string |Read Only| This is the raw cvv2 result code.                                                                   |
| orderId            | string |Read Only| Unique reference for the order. `ie: ORD_7915d463-ccc8-4305-9d33-9e5c9310f12e, SUB_c46645ea-b7b0-4a91-87f7-88c00ec0dea1`|
| profile            | [profile](#profileobject) |Read Only| This contains the customer details shared by the processor.                      |


<a name="profileobject" title="Profile Object"></a>
## profile

|Element            |Type                                                                                 |Required                                                                                                         |Description    |
|---                |---                                                                                  |---                                                                                                              |---            |
|locale             |enum                                                                                 |Required <br/> **Note:** Optional for CommercePro-Direct-Registration. Not required for Card Payouts.            |This indicates the language of the profile. Possible values are:<ul><li>en_US</li><li>fr_CA</li><li>en_GB</li></ul>|
|firstName          |string <br/>`length<=80`<br/>`For CommercePro, length<=20`                           |Required                                                                                                         |This is the customer’s first name. |
|lastName           |string <br/>`length<=80`<br/>`For CommercePro-Registration, length<=20`              |Required                                                                                                         |This is the customer’s last name. |
|email              |string<br/>`length<=255`  <br/>`For CommercePro-Registration, length<=20`            |Required                                                                                                         |This is the customer's email address.|
|phone              |string<br/>`length<=40`   <br/>`For CommercePro, min=10 max=15`                      |Required <br/> **Note:** Optional for CommercePro. Not required for Kensium Card Payouts.                            |This is the customer's phone number.|
|dateOfBirth        |dateOfBirth                                                                          |Required <br/> **Note:** Optional for payment.                                                                   |This is the customer's date of birth.|
|identityDocuments  |object                                                                               |Required for CommercePro-Registration                                                                            |CommercePro registration process.|   

```apib
            {
              "locale" : "en_US",
              "firstName" : "John",
              "lastName" : "Smith",
              "email" : "john.smith@somedomain.com",
              "phone" : "713-444-5555"
              "dateOfBirth" : "04-25-1987"
             }
```


## Questions Collection [/questions]

### List All Questions [GET]

+ Response 200 (application/json)

        [
            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 2048
                    }, {
                        "choice": "Python",
                        "votes": 1024
                    }, {
                        "choice": "Objective-C",
                        "votes": 512
                    }, {
                        "choice": "Ruby",
                        "votes": 256
                    }
                ]
            }
        ]

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }